---
- name: NFS Server
  hosts: nfs-servers
  become: yes
  remote_user: nadmin
  tasks:
    - name: server
      include_role:
        name: server
  tags: nfsserver

- name: NFS Client
  hosts: nfs-clients
  become: yes
  remote_user: nadmin
  tasks:
    - name: client
      include_role:
        name: client
  tags: nfsclient 



